name: helm_desk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
    
  #! Core
  flutter_secure_storage: ^9.2.4
  flutter_localization: ^0.3.3
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  collection: ^1.19.1
  app_links: ^6.4.1
  logger: ^2.6.2
  intl: ^0.20.2

  #! Image
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  path: ^1.9.1

  #! Network
  internet_connection_checker: ^3.0.1
  dio: ^5.9.0

  #! State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  dartz: ^0.10.1

  #! Notifications
  flutter_local_notifications: ^19.4.2
  firebase_messaging: ^16.0.2
  firebase_core: ^4.1.1
  
  #! View
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  flutter_spinkit: ^5.2.2
  pull_to_refresh: ^2.0.0
  flutter_svg: ^2.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.3
  flutter_gen_runner: ^5.12.0

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
  - assets/lang/
  # - assets/images/
  - assets/vectors/

  fonts:
  - family: Poppins
    fonts:
    - asset: assets/fonts/poppins/Poppins-Black.ttf
      weight: 900
    - asset: assets/fonts/poppins/Poppins-Bold.ttf
      weight: 700
    - asset: assets/fonts/poppins/Poppins-Medium.ttf
      weight: 500
    - asset: assets/fonts/poppins/Poppins-Regular.ttf
      weight: 400
    - asset: assets/fonts/poppins/Poppins-Light.ttf
      weight: 300
  - family: QomraArabic
    fonts:
    - asset: assets/fonts/qomra/itfQomraArabic-Black.ttf
      weight: 900
    - asset: assets/fonts/qomra/itfQomraArabic-Bold.ttf
      weight: 700
    - asset: assets/fonts/qomra/itfQomraArabic-Medium.ttf
      weight: 500
    - asset: assets/fonts/qomra/itfQomraArabic-Regular.ttf
      weight: 400
    - asset: assets/fonts/qomra/itfQomraArabic-Light.ttf
      weight: 300